apiVersion: v1
kind: Pod
metadata:
  name: envoy-playground
  labels:
    app: envoy-playground
spec:
  containers:
  - name: playground
    image: itaysk/envoy-playground:latest
    imagePullPolicy: IfNotPresent
    env:
    - name: PORT
      value: "8080"
    - name: FILEPATH
      value: "/etc/envoy/envoy.yaml"
    - name: ENVOY_LISTENER_PORT
      valueFrom:
        configMapKeyRef:
          name: envoy-playground-config
          key: serviceDiscovery.envoyListenerPort
    ports:
    - containerPort: 8080
      name: playground
    volumeMounts:
    - mountPath: /etc/envoy
      name: envoy-config
  - name: httpbin
    image: citizenstig/httpbin:latest
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 8000
  - name: envoy
    image: envoyproxy/envoy:latest
    imagePullPolicy: IfNotPresent
    args:
      - /usr/local/bin/envoy 
      - --v2-config-only 
      - -c 
      - /etc/envoy/envoy.yaml
    ports:
    - containerPort: 9901
      name: admin
    - containerPort: 10000
      name: listener0
    securityContext:
      runAsUser: 1337
    volumeMounts:
    - mountPath: /etc/envoy
      name: envoy-config
  volumes:
  - name: envoy-config
    emptyDir:
      medium: Memory
