apiVersion: v1
kind: Service
metadata:
  name: envoy-playground
  labels:
    app: envoy-playground
spec:
  ports:
    - name: envoyadmin
      port: 9901
      targetPort: 9901
    - name: envoy0
      port: 10000
      targetPort: 10000
    - name: playground
      port: 8080
      targetPort: 8080
    - name: httpbin
      port: 8000
      targetPort: 8000
  selector:
    app: envoy-playground
  type: NodePort